// frontend/app/pages/ims/databases/index.vue
<script setup lang="ts">
definePageMeta({
    layout: 'ims'
})

const { createDatabase  } = useDatabase()

</script>

<template>
    <div class="content-header container-flex">
        <section>
            <UIDropdown>
                <template #btn>
                    <UIButton icon-left="add" label="Create" variant="accent" />
                </template>
                <template #body>
                    <UIButton label="Folder" icon-left="addFolder" :small="true" variant="transparent" :disabled="true" />
                    <hr>
                    <UIButton label="Database" icon-left="database" :small="true" variant="transparent" @click="createDatabase()" />
                </template>
            </UIDropdown>
        </section>
        <section>
            
        </section>
    </div>
</template>

// src/app/databases/page.tsx
import HmnButton from "@/components/HmnButton";
import HmnDropdown from "@/components/HmnDropdown";


export default function Databases() {
  return (
    <div id="ims-content">
      <div id="functional-panel" className="container-flex">
        <section>
          <HmnDropdown label="Create" iconLeft="add" type="accent" alignment="left">
            <HmnButton label="Database" iconLeft="database" link="/databases/new" />
            <HmnButton label="Folder" iconLeft="addFolder" disabled={true} />
          </HmnDropdown>
        </section>
        <section>
          
        </section>
      </div>
    </div>
  );
}
