// frontend/app/pages/databases/index.vue
<template>
    <div id="content-ims">
        <div id="content-ims-functional-panel" class="container-flex">
            <section>
                <elements-dropdown-menu label="Create" variant="accent" icon="add" iconSide="right" alignment="left">
                    <template #>
                        <elements-button class="primary" icon="database" label="Database" to="/databases/new" />
                        <elements-button class="primary" icon="addFolder" label="Folder" :disabled="true" />
                    </template>
                </elements-dropdown-menu>
            </section>
            <section>

            </section>
        </div>
        <div id="content-ims-body">

        </div>
    </div>
</template>

// src/app/databases/page.tsx
import HmnButton from "@/components/HmnButton";
import HmnDropdown from "@/components/HmnDropdown";


export default function Databases() {
  return (
    <div id="ims-content">
      <div id="functional-panel" className="container-flex">
        <section>
          <HmnDropdown label="Create" iconLeft="add" type="accent" alignment="left">
            <HmnButton label="Database" iconLeft="database" link="/databases/new" />
            <HmnButton label="Folder" iconLeft="addFolder" disabled={true} />
          </HmnDropdown>
        </section>
        <section>
          
        </section>
      </div>
    </div>
  );
}
