// app/pages/reports/index.vue
<template>
    <div id="content-header">
        <section>
            <UiHmnDropdown>
                <template #btn>
                    <UiHmnButton icon-left="add" label="Create" variant="accent" />
                </template>
                <template #body>
                    <UiHmnButton icon-left="addFolder" label="Folder" variant="transparent" :small="true" :disabled="true" />
                    <hr>
                    <UiHmnButton icon-left="report" label="Report" variant="transparent" :small="true" :disabled="true" />
                </template>
            </UiHmnDropdown>
            
        </section>
        <section>
            
        </section>
    </div>
    <div id="content-body">
        
    </div>
</template>

// src/app/reports/page.tsx
import HmnButton from "@/components/HmnButton";
import HmnDropdown from "@/components/HmnDropdown";


export default function Reports() {
  return (
    <div id="ims-content">
      <div id="functional-panel" className="container-flex">
        <section>
          <HmnDropdown label="Create" iconLeft="add" type="accent" alignment="left">
            <HmnButton label="Report" iconLeft="report" disabled={true} />
            <HmnButton label="Folder" iconLeft="addFolder" disabled={true} />
          </HmnDropdown>
        </section>
        <section>
          
        </section>
      </div>
    </div>
  );
}
