// app/pages/ims/reports/index.vue
<script setup lang="ts">
definePageMeta({
    layout: 'ims'
})
</script>

<template>
    <div class="content-header container-flex">
        <section>
            <UIDropdown>
                <template #btn>
                    <UIButton icon-left="add" label="Create" variant="accent" />
                </template>
                <template #body>
                    <UIButton label="Folder" icon-left="addFolder" :small="true" variant="transparent" :disabled="true" />
                    <hr>
                    <UIButton label="Report" icon-left="report" :small="true" variant="transparent" :disabled="true" />
                </template>
            </UIDropdown>
        </section>
        <section>
            
        </section>
    </div>

    <div class="content-body">

    </div>
</template>

// src/app/reports/page.tsx
import HmnButton from "@/components/HmnButton";
import HmnDropdown from "@/components/HmnDropdown";


export default function Reports() {
  return (
    <div id="ims-content">
      <div id="functional-panel" className="container-flex">
        <section>
          <HmnDropdown label="Create" iconLeft="add" type="accent" alignment="left">
            <HmnButton label="Report" iconLeft="report" disabled={true} />
            <HmnButton label="Folder" iconLeft="addFolder" disabled={true} />
          </HmnDropdown>
        </section>
        <section>
          
        </section>
      </div>
    </div>
  );
}
