// frontend/app/pages/databases/new.vue
<template>
    <div id="content-ims">
        <div id="content-ims-functional-panel" class="container-flex">
            <section>
                
            </section>
            <section>
                <elements-button class="accent mbl" label="Save" icon="save" :disabled="true" />
            </section>
        </div>
        <div id="content-ims-body">

        </div>
    </div>
</template>

// src/app/databases/new/page.tsx
import HmnButton from "@/components/HmnButton";

export default function Databases() {
  return (
    <div id="ims-content">
      <div id="functional-panel" className="container-flex">
        <section>
          
        </section>
        <section>
          <HmnButton label="Save" iconLeft="save" type="accent" disabled={true} />
        </section>
      </div>
    </div>
  );
}
